export const ocrschema = {
  nik: "nik pada ktp pemohon",
  no_kk: "no kk pada kk pemohon",
  fullname: "nama lengkap pemohon (berdasarkan IDPB atau KTP)",
  birtdate: "tanggal lahir pemohon (berdasarkan IDPB atau KTP)",
  birtplace: "tempat lahir pemohon (berdasarkan IDPB atau KTP)",
  gender: "jenis kelamin pemohon",
  religion: "agama pemohon",
  ktp_date: "tanggal ktp",
  ktp_expires:
    "masa berlaku ktp, jika seumur hidup maka isi sama dengan tanggal lahir tapi tahun 2999",
  ktp_address: "alamat pemohon sesuai ktp",
  ktp_rt: "rt pemohon sesuai ktp",
  ktp_rw: "rw pemohon sesuai ktp",
  ktp_ward: "kelurahan pemohon sesuai ktp",
  ktp_district: "kecamatan pemohon sesuai ktp",
  ktp_city: "kota pemohon sesuai ktp",
  ktp_province: "provinsi pemohon sesuai ktp",
  ktp_pos_code: "kodepos pemohon sesuai ktp",
  current_address: "alamat pemohon sesuai domisili",
  current_rt: "rt pemohon sesuai domisili",
  current_rw: "rw pemohon sesuai domisili",
  current_ward: "kelurahan pemohon sesuai domisili",
  current_district: "kecamatan pemohon sesuai domisili",
  current_city: "kota pemohon sesuai domisili",
  current_province: "provinsi pemohon sesuai domisili",
  current_pos_code: "kodepos pemohon sesuai domisili",
  education: "pendidikan pemohon sesuai KK",
  marriage_status: "status kawin di KTP. (LAJANG/KAWIN/JANDA/DUDA",
  salary: "number ambil gaji takehomepay di IBPB",
  mothername: "nama ibu kandung di KK",
  aw_name: "nama ahliwaris sesuai KTP Ahliwaris",
  aw_nik: "nik ahliwaris sesuai KTP Ahliwaris",
  aw_ktp_date: "tangal ktp sesuai KTP Ahliwaris",
  aw_ktp_expires:
    "masa berlaku ktp sesuai KTP Ahliwaris, jika seumur hidup maka isi sama dengan tanggal lahir tapi tahun 2999",
  aw_address: "alamat ahliwaris sesuai KTP Ahliwaris",
  aw_rt: "rt ahliwaris sesuai KTP Ahliwaris",
  aw_rw: "rw ahliwaris sesuai KTP Ahliwaris",
  aw_ward: "kelurahan ahliwaris sesuai KTP Ahliwaris",
  aw_district: "kecamatan ahliwaris sesuai KTP Ahliwaris",
  aw_city: "kota ahliwaris sesuai KTP Ahliwaris",
  aw_province: "provinsi ahliwaris sesuai KTP Ahliwaris",
  aw_pos_code: "kodepos ahliwaris sesuai KK Ahliwaris/Pemohon",
  aw_phone: "no telepon ahliwaris",
  aw_relate:
    "hubungan keluarga pemoon dengan ahliwaris pada form pengajuan kredit",
  family_name: "nama keluarga tidak serumah pada form pengajuan kredit",
  family_address: "alamat keluarga tidak serumah pada form pengajuan kredit",
  family_rt: "rt keluarga tidak serumah pada form pengajuan kredit",
  family_rw: "rw keluarga tidak serumah pada form pengajuan kredit",
  family_ward: "kelurahan keluarga tidak serumah pada form pengajuan kredit",
  family_district:
    "kecamatan keluarga tidak serumah pada form pengajuan kredit",
  family_city: "kota keluarga tidak serumah pada form pengajuan kredit",
  family_province: "provinsi keluarga tidak serumah pada form pengajuan kredit",
  family_pos_code: "kode pos keluarga tidak serumah pada form pengajuan kredit",
  family_phone: "no telepon keluarga tidak serumah pada form pengajuan kredit",
  family_relate:
    "hubungan keluarga pemohon dengan keluarga tidak serumah pada form pengajuan kredit (jika lainnya maka isi dengan data yang sesuai)",
  npwp: "nomor npwp pemohon sesuai format aslinya",
  work_year: "masa kerja sesuai SK Pensiun pemohon (isi 0 jika tidak ada)",
  house_status:
    "status kepemilihan rumah pada form pengajuan kredit (MILIK_SENDIRI/SEWA/KONTRAK/KOS/MILIK_KELUARGA)",
  house_year: "tahun menempati rumah pada form pengajuan kredit",
  curr_job: "pekerjaan saat ini sesuai KTP",
  purpose_use: "RENOVASI RUMAH",
  bussines: "LAINNYA",
  nopen: "nomor pensiun pada IDPB/SK Pensiun",
  no_skep: "nomor SK Pensiun pensiun pada IDPB/SK Pensiun",
  name_skep: "nama sesuai IDPB/SK Pensiun",
  date_skep: "tanggal SK pensiun sesuai IDPB/SK Pensiun",
  tmt_skep: "TMT Pensiun  sesuai IDPB/SK Pensiun",
  soul_code: "kode jiwa sesuai IDPB/SK Pensiun",
  rank_skep: "pangkat sesuai IDPB/SK Pensiun",
  publisher_skep: "penerbi SK Pensiun sesuai IDPB/SK Pensiun",
  group_skep:
    "Kelompok/pengelola pensiun sesuai IDPB/SK Pensiun/Form Pengajuan Kredit",
  pay_office: "juru bayar asal sesuai IDPB/Form pengajuan kredit",
  mutasi_to: "juru bayar tujuan sesuai Form pengajuan kredit",
  instansi_takeover:
    "nama instansi sesuai Form pengajuan kredit bagian DATA PEMBIAYAAN DI LEMBAGA KEUANGAN LAINNYA (pisahkan dengan , jika lebih dari satu)",
  nominal_takeover:
    "number jumlah sisa pinjaman sesuai Form pengajuan kredit bagian DATA PEMBIAYAAN DI LEMBAGA KEUANGAN ILAINNYA",
};
